file_format: 'pdb' # cif or pdb
model_checkpoint: "facebook/esm2_t6_8M_UR50D" # esm2 model checkpoint
adapter: "./MLM_lora/model/mlm_conoserver_lora_esm2_t6_8M_UR50D" # MLM_lora model checkpoint

# training
pdb_path: "ctx_target/data/train_data/structure"
train_path: "ctx_target/data/train_data/train_fold5.csv"
unlabel_path: "ctx_target/data/train_data/unlabel_data.csv"
val_path: "ctx_target/data/train_data/test_fold5.csv"

device: "cuda:0"
epochs: 300
batch_size: 256
unlabeled_batch_size: 64
learning_rate: 0.01
d_model: 320
nhead: 1
num_encoder_layers: 1
dim_feedforward: 256
dropout: 0.1
ema_alpha: 0.999
clip_loss_weight: 1
weight_decay: 1e-4
consistency: 0.1
consistency_rampup: 1000
max_len: 50

# pre
test_path: "ctx_target/data/test_data/conopeptide.csv"
test_pdb_path: "ctx_target/data/test_data/structure"
best_model: "ctx_target/model/ctx_target_best_model.pth"
output: "ctx_target/output.csv"