base_model_path: "./esm2_base_model/esm2_t30_150M_UR50D" # esm2
adapter: "./MLM_lora/model/mlm_conoserver_lora_esm2_t30_150M_UR50D" # MLM_lora model checkpoint

# training
seed: 4
device: "cuda:0"
KFold: 10
epochs: 1000
lr: 0.001
batch_size: 1024
early_stop_patience: 300
log: "log.txt"
train_data: "conopep_ident/data/train_data.csv"
model_path: "conopep_ident/model/" # save path of model

# pre
min_len: 10 # min length of seq
max_len: 200 # max length of seq
evalue: 0.001
input_path: "conopep_ident/query_data/"
save_path: "conopep_ident/output/"
best_model_path: "conopep_ident/model/conopep_ident_best_model.pth"
superfamily_db: "conopep_ident/DB/superfamily/superfamily"  # superfamily hmm
family_db: "conopep_ident/DB/family/familys" # family hmm

# signal
signal: True # whether use signal pep
signal_db: "conopep_ident/DB/signal_pep.fasta"
published_db: "conopep_ident/DB/conotoxin_all4blast.fasta"


